<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-01-20 13:08

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('flvplayer2');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_flvplayer2_helper_youtube' => $extensionClassesPath . 'Helper/YouTube.php',
);
?>